version: '2'
services:
    mongotest:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: mongotest
      image: sysdig-example5-mongotest
      links:
          - mongodb
      depends_on:
          - mongodb
    mongodb:
      build:
        context: .
        dockerfile: Dockerfile-mongodb
      container_name: mongodb
      image: sysdig-example5-mongodb
      ports:
          - 27017:27017
      command: mongod --smallfiles --logpath=/dev/null # --quiet
